PromoSquad/promotions

- README.md
> Added travis badge on README.md

- service/models.py
- tests/test_promotions.py
> #72 | Ziyang | Add find promotion models by status

- service/models.py
- service/routes.py
- tests/test_routes.py
> #67 | Ziyang | Add active status query to list all API

- .github/workflows/test.yml
> #57 | Ziyang | Setup GitHub Actions

- README.md
- setup.cfg
> #82 | Ziyang | Add code coverage badge to README.md

- Vagrantfile
Changed private network ip address
from:
config.vm.network "private_network", ip: "192.168.33.10"
to:
config.vm.network "private_network", ip: "192.168.56.10"
See slack #homework for more detail
> Update Vagrantfile : 

- CONTRIBUTING.md
- README.md
- Vagrantfile
> #69 | Ziyang | Switch to 8080 as service port

- README.md
> #80 | Ziyang | Switch to GitHub Actions badge in README.md

- service/routes.py
- tests/test_routes.py
This is untested. The coverage is dropped by 2.8% by this pull request.
> Revert "modify routes.py to add the new function of activate with put method"

- README.md
- requirements.txt
> Replay #90 Pull Request due to hard revert

- README.md
> #99 | Ziyang | Keep README.md update to date with current service usage

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
> #114 | Ziyang | Add .devcontainer folder

- CONTRIBUTING.md
- Vagrantfile
- features/environment.py
- features/promotions.feature
- features/steps/promotions_steps.py
- features/steps/web_steps.py
- requirements.txt
- service/models.py
- service/static/index.html
> #102 | Ziyang | Setup BDD skeleton and basic tests

- .devcontainer/devcontainer.json
- features/promotions.feature
- features/steps/web_steps.py
- service/static/index.html
> #113 and #103 | Ziyang | Create and list all BDD features 

- .vscode/settings.json
- CONTRIBUTING.md
- README.md
- config.py
- features/steps/promotions_steps.py
- requirements.txt
- service/__init__.py
- service/error_handlers.py
- service/models.py
- service/routes.py
- service/static/index.html
- service/static/js/api.js
- tests/test_db_error.py
- tests/test_promotions.py
- tests/test_routes.py
Closes #108.
Closes #110.
Closes #111.
> #108, #110, #111 | Ziyang | Refactor the service using RESTX and setup Swagger

- features/promotions.feature
> #105 | Ziyang | Add Query promotions by Product ID to BDD Scenarios

- features/promotions.feature
> #112 | Tingting | Delete a promotion BDD test

- features/promotions.feature
> #104 | Ziyang | Add "query by status" BDD features

- features/promotions.feature
> #109 | Ziyang | Add "Update a promotion" BDD scenario

- service/static/index.html
> #130 | Ziyang | Fix wrong status shown in search result

- .github/workflows/test.yml
> #133 | Ziyang | Run BDD test in GitHub Actions 

- CONTRIBUTING.md
- README.md
> #131 | Ziyang | Add prod link to README.md and modify CONTRIBUTING.md
